### ISSUE TITLE
Buffer underflow issue

### ISSUE THREAD

**Issue by medamarko** [MrBuddyCasino/ESP32_MP3_Decoder#55]
Constantly getting buffer underflow.... Im using ESP Wroom 32 module. Do i need Wrover with PSram to run this app?

` (164423) mad_decoder: Buffer underflow, need 2471 bytes`

**Comment by khabte** [comment]
I ran into the exact same issue.

Calling [i2s_write](https://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/i2s.html#_CPPv29i2s_write10i2s_port_tPKv6size_tP6size_t10TickType_t) instead of the deprecated function [i2s_push_sample](https://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/i2s.html#_CPPv215i2s_push_sample10i2s_port_tPKv10TickType_t) seems to fix it for me. 

https://github.com/MrBuddyCasino/ESP32_MP3_Decoder/blob/580bbb94a4d0c0729af50d942941a616f925f93a/components/audio_renderer/audio_renderer.c#L194

I'll create a PR with the changes.

**Comment by myzhan** [comment]
I met the same issue, and this patch solved it.
